### PR TITLE
remove deprecated code

### PR DESCRIPTION
**Pull request by juliannzhou**
This PR removes any code that's marked deprecated as part of v2.

J=SLAP-2331
TEST=manual

Test: removed code that's tagged deprecated and files named deprecate, updated the documentations, and searched 'deprecate', 'answers', as well as all identifiers in Alex's renaming prs such as `AnswersError `, `AnswersRequest`, `AnswersConfig`, etc, and deleted anything that's deprecated.

### CODE REVIEW

**Review by nmanu1 — COMMENTED** [review]
there's a link in the README for the HH guide that still has "answers" in the url. can that be updated to "search" now?

**Review by nmanu1 — APPROVED** [review]
🔥

**Review by nmanu1 — COMMENTED** [review]
not sure if you need to publish a new alpha to remove the re-exports in headless

**Comment by juliannzhou** [comment]
> not sure if you need to publish a new alpha to remove the re-exports in headless

Okay, I will double check if it's needed!

**Pull request merged**
