### PR TITLE
Version 1.8.0

### PR DESCRIPTION
**Pull request by alextaing**
## Version 1.8.0
`@yext/answers-core` is now `@yext/search-core`!  This means that much of the `answers` terminology is now deprecated and have been replaced by new `search` terms.
### Changes
- The following identifiers were renamed in (https://github.com/yext/search-core/pull/185):
  - `AnswersCore` &rarr; `SearchCore`
  - `AnswersError` &rarr; `SearchError`
  - `AnswersRequest` &rarr; `SearchRequest`
  - `AnswersConfig` &rarr; `SearchConfig`
  - `BaseAnswersConfig` &rarr;`BaseSearchConfig`
  - `AnswersConfigWithApiKey` &rarr; `SearchConfigWithApiKey`
  - `AnswersConfigWithToken` &rarr; `SearchConfigWithToken`
  - `AnswersConfigWithDefaulting` &rarr; `SearchConfigWithDefaulting`
- `ANSWERS_CORE` was _not_ replaced with `SEARCH_CORE` for `search-core` agent info.

### CODE REVIEW

**Comment by oshi97** [comment]
I kind of like the way you wrote the release note here since it's a single change, but I would probably still make them match a little more closely with the notes from https://github.com/yext/search-core/pull/169 or https://github.com/yext/search-core/pull/75. Which is to say I would add a header like `### Changes` and make the one change a bullet point

**Review by nmanu1 — COMMENTED** [review]
the `package.json` version should be updated

**Comment by oshi97** [comment]
Actually I really like how you listed out the changed identifiers here https://github.com/yext/search-core/pull/185
I would probably just copy paste this commit message's bullet points

**Comment by oshi97** [comment]
I might even change `answers-core` and `search-core` to `@yext/answers-core` and `@yext/search-core` since those are the official package names on npm

**Comment by oshi97** [comment]
Could you add something about `Note that ANSWERS_CORE was not renamed SEARCH_CORE for agent info.`?

**Review by oshi97 — APPROVED** [review]

**Pull request merged**
